Models/AuthDbContext.cs
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;

namespace AuthenticationVideoOne.Models;

public class AuthDbContext : IdentityDbContext
{
    public AuthDbContext(DbContextOptions<AuthDbContext> options) : base(options)
    {

    }
}

ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace AuthenticationVideoOne.ViewModels;

public class Login
{
    [Required]
    [DataType(DataType.EmailAddress)]
    public string? Email { get; set; }
    [Required]
    [DataType(DataType.Password)]
    public string? Password { get; set; }
    public bool RememberMe { get; set; }
}

ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;

namespace AuthenticationVideoOne.ViewModels;

public class Register
{
    [Required]
    [DataType(DataType.EmailAddress)]
    public string? Email { get; set; }
    [Required]
    [DataType(DataType.Password)]
    public string? Password { get; set; }
    [Required]
    [DataType(DataType.Password)]
    [Compare(nameof(Password), ErrorMessage = "Password not match!")]
    public string? ConfirmPassword { get; set; }
}

Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AuthenticationVideoOne.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;

namespace AuthenticationVideoOne.Pages;

[Authorize]
public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using AuthenticationVideoOne.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace AuthenticationVideoOne.Pages;

public class LoginModel : PageModel
{
    [BindProperty]
    public Login Login { get; set; }
    public SignInManager<IdentityUser> SignInManager { get; set; }

    public LoginModel(SignInManager<IdentityUser> signInManager)
    {
        Login = new();
        SignInManager = signInManager;
    }

    public IActionResult OnGet()
    {
        return Page();
    }

    public async Task<IActionResult> OnPostAsync(string? returnUrl = null)
    {
        if (ModelState.IsValid)
        {
            var result = await SignInManager.PasswordSignInAsync(Login.Email, Login.Password, Login.RememberMe, false);

            if (result.Succeeded)
            {
                if (returnUrl == null || returnUrl == "/")
                {
                    return RedirectToPage("Index");
                }
                else
                {
                    return RedirectToPage(returnUrl);
                }
            }

            ModelState.AddModelError("", "Username or password incorrect");
        }

        return Page();
    }
}

Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;

namespace AuthenticationVideoOne.Pages;

public class LogoutModel : PageModel
{
    public SignInManager<IdentityUser> SignInManager { get; set; }
    public LogoutModel(SignInManager<IdentityUser> signInManager)
    {
        SignInManager = signInManager;
    }

    public async Task<IActionResult> OnPostLogoutAsync()
    {
        await SignInManager.SignOutAsync();
        return RedirectToPage("Login");
    }

    public IActionResult OnPostDontLogout()
    {
        return RedirectToPage("Index");
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Authorization;

namespace AuthenticationVideoOne.Pages;

[Authorize]
public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

Pages/Register.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc;
using AuthenticationVideoOne.ViewModels;
using Microsoft.AspNetCore.Identity;

namespace AuthenticationVideoOne.Pages;

public class RegisterModel : PageModel
{
    [BindProperty]
    public Register Register { get; set; }

    public UserManager<IdentityUser> UserManager { get; set; }
    public SignInManager<IdentityUser> SignInManager { get; set; }

    public RegisterModel(
        UserManager<IdentityUser> userManager,
        SignInManager<IdentityUser> signInManager)
    {
        Register = new Register();
        UserManager = userManager;
        SignInManager = signInManager;
    }

    public IActionResult OnGet()
    {
        return Page();
    }

    public async Task<IActionResult> OnPostAsync()
    {
        if (ModelState.IsValid)
        {
            var user = new IdentityUser
            {
                UserName = Register.Email,
                Email = Register.Email
            };

            var result = await UserManager.CreateAsync(user, Register.Password);

            if (result.Succeeded)
            {
                await SignInManager.SignInAsync(user, false);

                return RedirectToPage("Index");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
        }

        return Page();
    }
}

Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Pages/Login.cshtml
@page
@model AuthenticationVideoOne.Pages.LoginModel

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Login</h1>
            <form method="post">
                <div class="text-danger" asp-validation-summary="All"></div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Login.Email"></label>
                    <input class="form-control" type="email" asp-for="Login.Email" />
                    <span class="text-danger" asp-validation-for="Login.Email"></span>
                </div>
                <div class="mb-3">
                    <label class="form-label" asp-for="Login.Password"></label>
                    <input class="form-control" type="password" asp-for="Login.Password" />
                    <span class="text-danger" asp-validation-for="Login.Password"></span>
                </div>
                <div class="mb-3">
                    <input class="form-check-input" type="checkbox" asp-for="Login.RememberMe"/>
                    <label class="form-check-label" asp-for="Login.RememberMe"></label>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
        </div>

    </div>
</div>

Pages/Logout.cshtml
@page
@model AuthenticationVideoOne.Pages.LogoutModel

<form method="post">
    <div class="row justify-content-center">
        <p>Are you sure want to logout</p>
        <p>
            <button class="btn btn-danger" asp-page-handler="Logout">Yes</button>
            <button class="btn btn-secondary" asp-page-handler="DontLogout">No</button>
        </p>
    </div>
</form>

Pages/Register.cshtml
@page
@model AuthenticationVideoOne.Pages.RegisterModel
@{
}

<div class="container mt-5">
    <div class="row justify-content-center align-items-center">
        <div class="col-sm-12 col-md-12 col-lg-4">
            <h1 class="mb-3">Register</h1>
            <form method="post">
                <div asp-validation-summary="All" class="text-danger"></div>
                <div class="mb-3 form-group">
                    <label class="form-label" asp-for="Register.Email"></label>
                    <input class="form-control" type="text" asp-for="Register.Email" />
                    <span asp-validation-for="Register.Email" class="text-danger"></span>
                </div>
                <div class="mb-3 form-group">
                    <label class="form-label" asp-for="Register.Password"></label>
                    <input class="form-control" type="password" asp-for="Register.Password" />
                    <span asp-validation-for="Register.Password" class="text-danger"></span>
                </div>
                <div class="mb-3 form-group">
                    <label class="form-label" asp-for="Register.ConfirmPassword"></label>
                    <input class="form-control" type="password" asp-for="Register.ConfirmPassword" />
                    <span asp-validation-for="Register.ConfirmPassword" class="text-danger"></span>
                </div>
                <div class="mb-3 form-group">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

Pages/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AuthenticationVideoOne</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AuthenticationVideoOne.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AuthenticationVideoOne</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav d-flex justify-content-end flex-grow-1">
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="" asp-page="/Logout">Logout</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul class="navbar-nav d-flex justify-content-end flex-grow-1">
                            <li class="nav-item">
                                <a class="btn btn-primary" asp-area="" asp-page="/Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="btn" asp-area="" asp-page="/Register">Register</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AuthenticationVideoOne - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>